export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'PremiumBank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../assets/images/undraw_developer_activity_bv83.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}